springdoc:
  api-docs:
    version: OPENAPI_3_0
spring:
  application:
    name: accounts
  datasource:
    url: jdbc:h2:mem:abc_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    enabled: true
    baseline-on-migrate: true
server:
  port: 8081
